version: '3.9'

services:
  node:
    container_name: vuepress-blog
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
    - NODE_ENV=production
    volumes:
    - ./:/home/node/app
    ports:
    - '8080:8080'
    command: /bin/sh -c "npm install --no-save --production=false && npm start"

networks:
  default:
    name: vuepress-blog-network
